sudo: required
dist: trusty
language: cpp
compiler: gcc
cache: ccache
addons:
  postgresql: 9.4
  apt:
    packages:
      - libboost-dev
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - libboost-locale-dev
      - libboost-program-options-dev
      - libboost-regex-dev
      - libboost-system-dev
      - libcrypto++-dev
      - libfcgi-dev
      - libmemcached-dev
      - libpqxx-dev
      - libxml2-dev
script:
  - ./autogen.sh
  - ./configure CC="ccache gcc" CXX="ccache g++"
  - make
  - make check
after_failure:
  - cat test-suite.log
